### ISSUE TITLE
deletions run from state, not from code

### ISSUE THREAD

**Issue by jrobison-sb** [aidanmelen/terraform-provider-snowsql#11]
### Terraform Version
```
$ terraform -v
Terraform v0.14.11
+ provider registry.terraform.io/aidanmelen/snowsql v0.2.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
- snowsql_exec

### Terraform Configuration Files
```
resource "snowsql_exec" "use_utc_timezone_for_account" {
  name  = "snowflake-timezone-parameter-utc"

  create {
    statements = <<-EOT
      ALTER ACCOUNT SET TIMEZONE = 'UTC'
    EOT
  }

  delete {
    statements = <<-EOT
      ALTER ACCOUNT UNSET TIMEZONE = 'UTC'
    EOT
  }

  delete_on_create = false
}
```

### Expected Behavior
Deletion statements are based on the terraform code at the time of apply.

### Actual Behavior
Deletion statements are based on the terraform state at the time of apply.

### Steps to Reproduce
1. Apply the above infrastructure, which uses invalid SQL for the deletion statement. It will apply correctly upon creation because the creation statement is valid SQL.
2. Use `terraform taint` or `terraform destroy` to attempt to destroy the above infrastructure. This will fail because the deletion statement isn't valid.
```
Error: 001003 (42000): SQL compilation error:
syntax error line 1 at position 29 unexpected '='.
```
3. You notice your mistake and fix your deletion statement. `ALTER ACCOUNT UNSET TIMEZONE`.
4. Use `terraform taint` or `terraform destroy` again, expecting it to work because you now have valid SQL. But it won't work because the deletion statement isn't coming from your now valid SQL, it's coming from the invalid SQL that's still in the state. You get the same error as above.
5. The only way to unblock yourself is to `terraform state rm ... && terraform import ...`, then try the deletion again. This is unintuitive because you're used to having changes in your code reflected in the actions terraform takes.

**Comment by aidanmelen** [comment]
Thanks @jrobison-sb for sharing your issue and sorry that was such a headache... I call these resources **zombie resources**.

I noticed that you have `delete_on_create = false`. Have you tried using `delete_on_create = true` to protect against this scenario?

Although `delete_on_create` doesn't protect the user from supplying a delete statement that fails to undo the create statement... it does ensure that the delete statement is syntactically valid. This would have prevented resource creation in the first place.

Please see the [documentation](https://registry.terraform.io/providers/aidanmelen/snowsql/latest/docs/resources/exec#delete-on-create-example) for more information.

At the very least, I would strongly encourage you to test your create and delete SQL statements in the Snowflake console before automating with this terraform provider.

That being said, this resource is intentionally dumb as there is no `Read` or `Update` logic whatsoever. `snowsql_exec` only implements `Create` and `Delete`. This would explain why the altered delete statement was not honored post create. I initially wanted to implement refresh functionality but I settled for the `delete_on_create` instead because i thought it added better protection for the end user. It is something that I could probably be convinced to revisit if you still felt `delete_on_create` was insufficient for your use case.

**Comment by jrobison-sb** [comment]
@aidanmelen thanks for your reply, and I do see the reference to zombie resources called out in the docs now. This might have been a case where my expectations were just inaccurate. Considering that the use case for this provider (one-off SQL execution) is quite different than most other providers (managing a bucket or whatever, in an ongoing fashion), it makes sense that the implementation is different. 

Thanks for the explanation. I'll close this issue now.

**Comment by aidanmelen** [comment]
I originally didn't implement the `Update` lifecycle because I was worried that users would unknowingly creating spurious Snowflake objects every time they successfully updated the `create.statements`.  That wouldn't be a great user experience.

However, I think having an `Update` lifecycle for the `delete.statements` would actually be useful for the case that you have encountered. This would give users the ability to delete the snowflake object using the `snowsql_exec` resource instead of perform state surgery manually.

I will make a PR in the coming weeks
